### ISSUE TITLE
Usage with a custom server

### ISSUE THREAD

**Issue by GGAlanSmithee** [apteryxxyz/next-ws#8]
Hi,

Is there an easy way to access the server socket when using a custom server?

Thanks for this awesome plugin and in advance for answering my question!

**Comment by apteryxxyz** [comment]
You want to be able to access the WebSocket server outside of a SOCKET route? There isn't currently anyway to do that I believe, but I'll look into it.

**Comment by GGAlanSmithee** [comment]
Thanks for your answer.

Yes, more specifically in a [custom server](https://nextjs.org/docs/pages/building-your-application/configuring/custom-server).

I'm my case, I need to run some cronjobs at startup which needs to access the socket, but it could also be useful for the more general case where you want to use the connected event for whatever reason.

**Comment by GGAlanSmithee** [comment]
I haven't actually looked at this myself, but since (I guess) this package monkey patches nextjs with was functionality, maybe the WS is already there?

**Comment by GGAlanSmithee** [comment]
@apteryxxyz I will put up an repo right away. 

interestingly, when actually testing this right now, it seems that next-ws is not compatible with next.js custom server at all atm.

Notice the different outcome in the image below when running `next dev` vs `node server.js`:

![image](https://github.com/apteryxxyz/next-ws/assets/11805103/4bad314a-b40b-4499-a8a6-b15d8d88df67)

**Comment by GGAlanSmithee** [comment]
Here is a repo to test with, just run `npm run dev`: https://github.com/GGAlanSmithee/nextjs-ws-custom-server

**Comment by apteryxxyz** [comment]
Yeah I get that error as well, it comes somewhere from `app.prepare()`.
Next ws grabs the http server from the server options of the next server, aka the object you pass to the `next` function. Even if you do pass the custom server to that, it doesn't exist on the server options next ws receives. I'm not too sure why.

**Comment by 55Cancri** [comment]
Not being able to use with custom server is also preventing me from adopting this package as well

**Comment by apteryxxyz** [comment]
I've just published an experimental version of Next WS (`next-ws@experimental`) that adds support for custom servers. It appears to work but it's not fully tested.

The way it works is by you assigning your own http server (and optionally ws server) to a global variable, which Next WS will check for when setting up the server. I'm not a fan of assigning to global, but I prefer this over having to patch more things in Next.js.

`CustomHttpServer`, `CustomWsServer` are two symbols that get exported from `next-ws/server` and can be used to assign your custom http server to the global object.

This is the setup I used:

```js
// server.js
const { Server } = require('http');
const { WebSocketServer } = require('ws');
const { parse } = require('url');
const next = require('next');
const { CustomHttpServer, CustomWsServer } = require('next-ws/server');

const dev = process.env.NODE_ENV !== 'production';
const hostname = 'localhost';
const port = 3000;

const httpServer = new Server();
global[CustomHttpServer] = httpServer;
const wsServer = new WebSocketServer({ noServer: true });
global[CustomWsServer] = wsServer;

const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  httpServer
    .on('request', async (req, res) => {
      const parsedUrl = parse(req.url, true);
      await handle(req, res, parsedUrl);
    })
    .listen(port, () => {
      console.log(` ▲ Ready on http://${hostname}:${port}`);
    });
});
```

Let me know if you try it and how it goes, I'll do more testing when I have more time.

**Comment by 55Cancri** [comment]
Thanks so much man, it seems to be working for me as well, even when creating https and wss servers. Some things I noticed:
- you still must run `pnpx next-ws-cli@latest patch`, even for custom server
- the servers must be attached at the global level (not created and attached within the app.prepare statement else the app will fail)
- package doesn't seem to have any esm exports, so if I set `type: "module"` in package.json, change to module export in next.config.js, and change all the require statements in server.js to import statements, then importing from next-ws/server fails.

Otherwise, the changes look good to me and I will use like this. Thanks again for doing this! So sad nextjs doesn't natively support websockets and makes it so difficult to include.

**Comment by apteryxxyz** [comment]
> you still must run `pnpx next-ws-cli@latest` patch, even for custom server

Yeah, there's a few reasons for this but the main is the Next WS needs access to the `NodeNextServer`. And there is no reliable (as in has everything Next WS needs) way that I know of to get that in the `server.js` file. There are a lot of "solutions" to the problems I encounter but they just cause more problems to arise, which is why I ended up going with using `global`.

> the servers must be attached at the global level

The WebSocket server is setup when `app.prepare` is called, so the custom HTTP server needs to be defined before that.

> package doesn't seem to have any esm exports

I've been meaning to replace compiling with TSC to tsup, I'll use that to add ESM exports. For the time being I could replace the `CustomHttpServer` symbol with a plain string so you don't have to grab it from the package in order to define.

**Comment by apteryxxyz** [comment]
I'll just published a new `next-ws@experimental` version, that replaces the custom symbols with strings so you no longer have to grab the symbols from the `next-ws` package.

This is my new `server.js` file:

```js
import { Server } from 'node:http';
import { parse } from 'node:url';
import next from 'next';
import { WebSocketServer } from 'ws';

const dev = process.env.NODE_ENV !== 'production';
const hostname = 'localhost';
const port = 3000;

const httpServer = new Server();
globalThis['NextWS::CustomHttpServer'] = httpServer;
const wsServer = new WebSocketServer({ noServer: true });
globalThis['NextWS::CustomWsServer'] = wsServer;

const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  httpServer
    .on('request', async (req, res) => {
      const parsedUrl = parse(req.url, true);
      await handle(req, res, parsedUrl);
    })
    .listen(port, () => {
      console.log(` ▲ Ready on http://${hostname}:${port}`);
    });
});
```

**Comment by GGAlanSmithee** [comment]
Thanks so much for doing this @apteryxxyz. I haven't been able to test this just yet, because I got caught up in a lot of work but I intend to test it ASAP

**Comment by Alex-Mastin** [comment]
I'm finding I have a somewhat similar use-case. I'm building an app that needs an external source to be able to send messages to the WebSocket server, but I'm hitting a wall in getting that working. I tried the above solution, and was able to get it working locally, but since my project is built in `standalone` mode (for Docker) it wasn't super clear how to use the custom server alongside the `server.js` that gets generated by Next. Also didn't really love losing TypeScript support to have a custom server.
